Feature/weather 8
IlyaTheCreator/weather pull request #2
Opened 2022-01-28 13:27 UTC by IlyaTheCreator

2022-01-28 13:43 UTC, skinet2009 requested changes

2022-01-28 13:43 UTC, skinet2009 commented on app/js/LsManager.js
> +        const newData = JSON.parse(localStorage.getItem(this.appKey));
Почему не используешь методы класса?

2022-01-28 13:43 UTC, skinet2009 commented on app/js/LsManager.js
> +            if (jsonItem === "length") {
Как по-другому можно сделать?

2022-01-28 13:47 UTC, IlyaTheCreator commented on app/js/LsManager.js
> +        const newData = JSON.parse(localStorage.getItem(this.appKey));
Использую: 
lsManager.set(setting, { ...settingsItemData, value: !settingsItemData.value});

(строка 73, файл index.js)

2022-01-31 05:30 UTC, skinet2009 commented on app/js/LsManager.js
> +        for (let jsonItem in localStorage) {
Изучи альтернативные способы итерации объектов.
Возможно, какой-то иной подход тебе понравится больше.
https://forxtu.space/5-ways-to-iterate-object/

2022-01-31 05:41 UTC, skinet2009 commented
![image](https://user-images.githubusercontent.com/7460114/151744490-9d1ef6c4-2013-4ed0-8ada-09a9b8830122.png)
Со стилями что-то не так.
Слева макет - справа вёрстка

2022-01-31 05:46 UTC, skinet2009 commented
![image](https://user-images.githubusercontent.com/7460114/151744837-db1c8820-6d50-43de-9934-7f9e14e3632a.png)
На странице имеется несколько скроллов, хотя ни один из них не нужен в данной ситуации,
Дополнительно, внизу есть пустое пространство.

2022-01-31 05:47 UTC, skinet2009 requested changes

2022-01-31 05:47 UTC, skinet2009 commented on app/js/index.js
> +        value: true
Если этот флаг отвечает за состояние, активен виджет или нет, то лучше придумать более подходящее для этого свойства название

2022-02-01 08:17 UTC, merged